# Generated by Django 3.1.5 on 2021-01-23 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210122_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=200)),
                ('Cat_descr', models.CharField(max_length=900)),
            ],
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place',
            new_name='place_name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='parent_category',
            new_name='parent_task',
        ),
        migrations.AddField(
            model_name='task',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.place'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_descr',
            field=models.CharField(default='Нет описания', max_length=900),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.category'),
        ),
    ]
