# Generated by Django 3.1.5 on 2021-01-23 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210123_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.place'),
        ),
    ]
