# Generated by Django 3.1.5 on 2021-01-23 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_place_parent_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Cat_descr',
            new_name='cat_descr',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Category',
            new_name='category_name',
        ),
    ]
