# Generated by Django 3.1.5 on 2021-01-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20210123_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='place',
        ),
        migrations.AddField(
            model_name='task',
            name='place',
            field=models.ManyToManyField(to='tasks.Place'),
        ),
    ]
