# Generated by Django 3.1.5 on 2021-01-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20210123_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='place',
        ),
        migrations.AddField(
            model_name='place',
            name='task',
            field=models.ManyToManyField(blank=True, to='tasks.Task'),
        ),
    ]
