# Generated by Django 3.1.5 on 2021-01-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20210123_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='place_in_task',
        ),
        migrations.AddField(
            model_name='task',
            name='place_in_task',
            field=models.ManyToManyField(blank=True, to='tasks.Place'),
        ),
    ]
