# Generated by Django 3.1.5 on 2021-01-23 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20210123_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='task_in_place',
        ),
        migrations.AddField(
            model_name='place',
            name='task_in_place',
            field=models.ManyToManyField(blank=True, null=True, to='tasks.Task'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='place_in_task',
        ),
        migrations.AddField(
            model_name='task',
            name='place_in_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.place'),
        ),
    ]
