# Generated by Django 3.1.5 on 2021-01-23 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20210123_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='place_in_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.place'),
        ),
    ]
