# Generated by Django 3.1.5 on 2021-01-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20210123_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='place_in_task',
            new_name='place',
        ),
    ]
