# Generated by Django 3.1.5 on 2021-01-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_auto_20210123_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='tasks',
            field=models.ManyToManyField(to='tasks.Task'),
        ),
    ]
